name = "youfoundthis"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
main = "dist/server/index.js"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "youfoundthis"
database_id = "0f888933-5557-4ef8-a31b-32684a62cc25"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "youfoundthis-photos"